// src/js/modules/api.js

/**
 * Parses the generated search query to separate recognized parameters from the main search term.
 * @param {string} query - The full search query string generated by the user.
 * @returns {object} An object containing parsed parameters.
 */
function parseAdvancedSearchParams(query) {
    const params = {
        srsearch: query,
        srincategory: '',
        srdeepcategory: '',
        srhastemplate: '',
        srprefix: '',
        srincontent: '',
        srfiletype: '',
    };

    const extractParam = (regex, paramName) => {
        const match = params.srsearch.match(regex);
        if (match && match[1]) {
            params[paramName] = match[1].replace(/^"|"$/g, '');
            params.srsearch = params.srsearch.replace(match[0], '').trim();
        }
    };

    extractParam(/incategory:("([^"]+)"|([^\s]+))/i, 'srincategory');
    extractParam(/deepcat:("([^"]+)"|([^\s]+))/i, 'srdeepcategory');
    extractParam(/hastemplate:("([^"]+)"|([^\s]+))/i, 'srhastemplate');
    extractParam(/prefix:("([^"]+)"|([^\s]+))/i, 'srprefix');
    extractParam(/insource:("([^"]+)"|([^\s]+))/i, 'srincontent');
    extractParam(/filetype:([^\s]+)/i, 'srfiletype');

    params.srsearch = params.srsearch.trim();
    return params;
}

/**
 * Performs a search on the Wikipedia API.
 * @param {string} query - The search query string.
 * @param {string} lang - The language of the Wikipedia to search.
 * @returns {Promise<Array>} A promise that resolves to an array of search results.
 */
export async function performWikipediaSearch(query, lang) {
    const endpoint = `https://${lang}.wikipedia.org/w/api.php`;
    const parsedParams = parseAdvancedSearchParams(query);

    const apiParams = {
        action: 'query',
        list: 'search',
        format: 'json',
        origin: '*',
        ...parsedParams
    };

    // Remove any empty parameters to keep the URL clean
    Object.keys(apiParams).forEach(key => {
        if (!apiParams[key]) {
            delete apiParams[key];
        }
    });

    const params = new URLSearchParams(apiParams);
    const url = `${endpoint}?${params}`;
    console.log("Wikipedia Search API URL:", url);

    try {
        const response = await fetch(url);
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        const data = await response.json();
        return data.query.search || [];
    } catch (error) {
        console.error("Error during Wikipedia search:", error);
        return [];
    }
}

/**
 * Fetches a brief summary for a given article title.
 * @param {string} title - The title of the article.
 * @param {string} lang - The language of the Wikipedia.
 * @returns {Promise<string>} A promise that resolves to the article summary.
 */
export async function fetchArticleSummary(title, lang) {
    const endpoint = `https://${lang}.wikipedia.org/w/api.php`;
    const params = new URLSearchParams({
        action: 'query',
        prop: 'extracts',
        exintro: true,
        explaintext: true,
        titles: title,
        format: 'json',
        origin: '*'
    });
    const url = `${endpoint}?${params}`;

    try {
        const response = await fetch(url);
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        const data = await response.json();
        const pages = data.query.pages;
        const pageId = Object.keys(pages)[0];
        // Handle cases where the page doesn't exist or has no extract
        if (pageId === "-1" || !pages[pageId].extract) {
            return "No summary available.";
        }
        return pages[pageId].extract;
    } catch (error) {
        console.error(`Could not fetch summary for ${title}:`, error);
        return "Summary could not be retrieved.";
    }
}
